### ISSUE TITLE
pushmi_pullyu startup problem

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/pushmi_pullyu#231]
When running 

``` systemctl start pmpy ```

if the redis queue is empty, we got the following error message dump:

<pre>
I, [2021-11-17T09:54:16.078464 #1607]  INFO -- : DEBUG:
/usr/lib64/ruby/gems/2.6.0/gems/json-2.6.1/lib/json/common.rb:216:in `initialize': no implicit conversion of nil into String (TypeError)
        from /usr/lib64/ruby/gems/2.6.0/gems/json-2.6.1/lib/json/common.rb:216:in `new'
        from /usr/lib64/ruby/gems/2.6.0/gems/json-2.6.1/lib/json/common.rb:216:in `parse'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:187:in `run_preservation_cycle'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:218:in `run_tick_loop'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:55:in `start_server'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:282:in `block in start_server_as_daemon'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:277:in `block in start_proc'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/daemonize.rb:84:in `call_as_daemon'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:281:in `start_proc'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:307:in `start'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/controller.rb:56:in `run'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons.rb:199:in `block in run_proc'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/cmdline.rb:124:in `catch_exceptions'
        from /usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons.rb:198:in `run_proc'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:280:in `start_server_as_daemon'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:35:in `run'
        from /usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/exe/pushmi_pullyu:7:in `<top (required)>'
        from /usr/bin/pushmi_pullyu:23:in `load'
        from /usr/bin/pushmi_pullyu:23:in `<main>'
I, [2021-11-17T09:54:17.140392 #3203]  INFO -- : Loading PushmiPullyu 2.0.1
I, [2021-11-17T09:54:17.140491 #3203]  INFO -- : Running in ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-linux]

</pre>

The service started with success, but if we can add a line to check if the returned object is nil prior to type conversion, it will avoid the dump of error message.

**Comment by henryzhang87** [comment]
That error message was caused by systemctl restart pmpy.

closed
