### ISSUE TITLE
authenticate_http_call in aip/download.rb of PMPY

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/pushmi_pullyu#234]
In order to test if authenticate_http_call works as designed, I wrote a ruby script on the basis of the original PMPY authenticate_http_call method. The code is stored at middlesbrough:/var/pushmi_pullyu/auth.rb. It is copied and pasted below 

### a) test code for authenticate with api_key on the basis of the original code for PMPY in github

```
require 'net/http'
require 'uri'
require 'digest'
require 'json'

#
# code snippet 4 authentication from PMPY
#
"""
    @http = Net::HTTP.new(@uri.host, @uri.port)
    request = Net::HTTP::Post.new(@uri.request_uri + 'auth/system')
    request.set_form_data(
      email: PushmiPullyu.options[:jupiter][:user],
      api_key: PushmiPullyu.options[:jupiter][:api_key]
    )
    response = @http.request(request)
"""


#
# revised test code 4 authentication
#

# load user and api key from a json file
file = File.read('./auth.json')
cred = JSON.parse(file)

puts cred['email']
puts cred['api_key']

uri = URI.parse("https://era-test.library.ualberta.ca/")

http = Net::HTTP.new(uri.host, uri.port)

request= Net::HTTP::Post.new(uri.request_uri + 'auth/system')

request.set_form_data(
      email: cred['email'],
      api_key: cred['api_key']
)

res=http.request(request)

puts res.to_s


```

### b) user name and api_key value in auth.json

```
 "email": "ditech@ualberta.ca",
 "api_key": "MASKED OUT FOR SECURITY PURPOSE"
}
```

### c) execution of the script for the first time: connection reset by peer

```
[root@middlesbrough pushmi_pullyu]# ruby auth.rb
/usr/lib64/ruby/2.6.0/socket.rb:452:in `__read_nonblock': Connection reset by peer (Errno::ECONNRESET)
        from /usr/lib64/ruby/2.6.0/socket.rb:452:in `read_nonblock'
        from /usr/lib64/ruby/2.6.0/net/protocol.rb:210:in `rbuf_fill'
        from /usr/lib64/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
        from /usr/lib64/ruby/2.6.0/net/protocol.rb:201:in `readline'
        from /usr/lib64/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
        from /usr/lib64/ruby/2.6.0/net/http/response.rb:29:in `read_new'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `catch'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `transport_request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1479:in `request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1472:in `block in request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:920:in `start'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1470:in `request'
        from auth.rb:42:in `<main>'

```

### d) execution of the script for a second time: end of file reached

```
/usr/lib64/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
        from /usr/lib64/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
        from /usr/lib64/ruby/2.6.0/net/protocol.rb:201:in `readline'
        from /usr/lib64/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
        from /usr/lib64/ruby/2.6.0/net/http/response.rb:29:in `read_new'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `catch'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `transport_request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1479:in `request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1472:in `block in request'
        from /usr/lib64/ruby/2.6.0/net/http.rb:920:in `start'
        from /usr/lib64/ruby/2.6.0/net/http.rb:1470:in `request'
        from auth.rb:42:in `<main>'
```

## Questions:

1)  Do we have **auth/system** in the jupiter app as shown in ```request= Net::HTTP::Post.new(uri.request_uri + **'auth/system'**)```?

2)  When using basic authentication, we normally need to set ``` res.auth_basic username, password```, for api_key authorization, do we need explicitly set something?

3) where "aip_api_path=aip/v1" is used by the pmpy code?

**Comment by pgwillia** [comment]
1. This is our controller test of the `auth/system` 

https://github.com/ualbertalib/jupiter/blob/jupiter-2.1.0/config/routes.rb#L84

https://github.com/ualbertalib/jupiter/blob/270ecb395a59f4a1749158270be9661727f94f1d/test/controllers/sessions_controller_test.rb#L150-L159

3. Here's where `aip_api_path` is used https://github.com/ualbertalib/pushmi_pullyu/blob/41849df1f78add3cd3a4168bc3b9ed036c546862/lib/pushmi_pullyu/aip/downloader.rb#L126-L129

**Comment by henryzhang87** [comment]
Yesterday, when I tried to list the routes using

RAILS_ENV=staging rails routes

I got error messages.  

A moment ago, I did it again, it worked. A list of aip api can be obtained. 

```
[root@era-app-stg-1 jupiter]# RAILS_ENV=staging rails routes | grep "aip"
                    aip_v1_collection GET      /aip/v1/collections/:id(.:format)                                                        aip/v1/collections#show {:format=>:n3}
                        aip_v1_entity GET      /aip/v1/:entity/:id(.:format)                                                            aip/v1/entities#show {:format=>:n3}
               aip_v1_entity_filesets GET      /aip/v1/:entity/:id/filesets(.:format)                                                   aip/v1/entities#file_sets {:format=>:n3}
             aip_v1_entity_file_paths GET      /aip/v1/:entity/:id/file_paths(.:format)                                                 aip/v1/entities#file_paths {:format=>:n3}
               aip_v1_entity_file_set GET      /aip/v1/:entity/:id/filesets/:file_set_id(.:format)                                      aip/v1/entities#file_set {:format=>:n3}
         aip_v1_entity_fileset_fixity GET      /aip/v1/:entity/:id/filesets/:file_set_id/fixity(.:format)                               aip/v1/entities#fixity_file {:format=>:n3}

```

**Comment by pgwillia** [comment]
The login works for me
```
require 'uri'
require 'net/http'
require 'openssl'


url = URI("https://era-app-stg-1.library.ualberta.ca/auth/system?email=ditech@ualberta.ca&api_key=<api key>")

http = Net::HTTP.new(url.host, url.port)

http.use_ssl = true


request = Net::HTTP::Post.new(url)

request["Content-Type"] = 'application/vnd.api+json'


response = http.request(request)

puts response.code
puts response.read_body
```
=> 
200

**Comment by pgwillia** [comment]
There's a bug here.  The deployed code doesn't use `http.use_ssl = true`

**Comment by henryzhang87** [comment]
Thanks for figuring the bug out. 

I manually added the following lines to the pmpy aip/download.rb file.

```
    @http.use_ssl=true

    request = Net::HTTP::Post.new(@uri.request_uri + '/auth/system')
    request["Content-Type"] = 'application/vnd.api+json'
```

Re-enqueued the items, this time it passed the authentication phase based on the debug message "Henry Zhang: after authentication" as shown below

```
I, [2021-11-19T13:56:31.261539 #2228]  INFO -- : DEBUG: {"uuid":"2a73bb58-ffa8-4a02-be7e-852a68db888d","type":"items"}
I, [2021-11-19T13:56:31.264004 #2228]  INFO -- : [items - 2a84ef02-46e0-4660-ae6f-c04bb8e3fd1b]: Retreiving data from Jupiter ...
D, [2021-11-19T13:56:31.510697 #2228] DEBUG -- : Henry Zhang: after response #<Net::HTTPOK:0x0000000003fe25d8>
I, [2021-11-19T13:56:31.510835 #2228]  INFO -- : Henry Zhang: after authentication...
D, [2021-11-19T13:56:31.510877 #2228] DEBUG -- : [items - 2a84ef02-46e0-4660-ae6f-c04bb8e3fd1b]: Creating directories ...
D, [2021-11-19T13:56:31.512641 #2228] DEBUG -- : [items - 2a84ef02-46e0-4660-ae6f-c04bb8e3fd1b]: Creating directories done

```

However, we have some other problem, I will close this issue and create another one for another issue after passing authentication
