### ISSUE TITLE
undefined method `strip' for false:FalseClass (NoMethodError)

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/pushmi_pullyu#244]
On January 5, 2022, there are 12 items appeared in pullmi_pullyu.log-20220106.gz, but these items are not preserved in Swift

```
[root@chard log]# zcat pushmi_pullyu.log-20220106.gz | egrep "^E,"
E, [2022-01-05T13:58:07.569737 #30944] ERROR -- : Authentication failed with response code 403 (OpenStack::Exception::Authentication)
E, [2022-01-05T13:59:48.597272 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:01:32.007115 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:03:43.438633 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:05:34.528077 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:06:55.547014 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:08:46.598303 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:10:07.597540 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:12:58.720200 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:14:39.715110 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:16:40.781421 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-05T14:18:41.852715 #30944] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)

```

The corresponding items can be pushed into the queue and re-ingest again.  But why did the above happen? Seems to be related to authentication. Again, when preservation can't happen, the items failed need to be reinstated or kept on the queue

**Comment by henryzhang87** [comment]
To preserve the missing items, a temporary rake task was created:

```

  desc 'preserve objects by ids from an input file'
  task :preserve_object_by_ids, [:filename] => :environment do |_,args|

    if not args.filename.present?
       abort("please enter the file name containing ids")
    end

   ids=File.readlines(args.filename)

   for id in ids
    #item=Item.find_by(id: "#'{id.strip}'")
    item=Item.find_by(id: id.strip)
    if not item.nil?
      item.push_entity_for_preservation
    end

    thesis=Thesis.find_by(id: id.strip)
    if not thesis.nil?
      thesis.push_entity_for_preservation
    end
   end
  end

```

Using the above rake task, push the missing items into the redis queue

```
 RAILS_ENV=production rails  pmpy:preserve_object_by_ids['/root/era_assets/missing_ids_from_20210106.txt']
```

Verification of items being queued:

```
[root@acton ~]#  redis-cli -a ************ -n 1 zrange prod:pmpy_queue 0 100
 1) "{\"uuid\":\"a2c05b79-bd07-4dd5-9698-ee656c5acdd4\",\"type\":\"items\"}"
 2) "{\"uuid\":\"cf6ee377-d308-4a68-ac9f-e504a671f71a\",\"type\":\"items\"}"
 3) "{\"uuid\":\"e1716ddb-83fd-46f6-b385-9906b43e60ba\",\"type\":\"items\"}"
 4) "{\"uuid\":\"eac4c167-3d07-4426-a68e-f57281450dcc\",\"type\":\"items\"}"
 5) "{\"uuid\":\"f15b5db7-e9a4-44f8-9939-cc7cb4eaddfc\",\"type\":\"items\"}"
 6) "{\"uuid\":\"fba9795f-f620-4f43-9bf6-555f793232f0\",\"type\":\"items\"}"
 7) "{\"uuid\":\"2d6203d2-a368-4cf9-be53-8271183e222d\",\"type\":\"items\"}"
 8) "{\"uuid\":\"9e6b4af7-24b1-46b6-a542-8492cbbe6fdd\",\"type\":\"items\"}"
 9) "{\"uuid\":\"28ef32c1-7097-4bfd-871c-dfacbaec8415\",\"type\":\"items\"}"
10) "{\"uuid\":\"85a6c62a-d901-4517-af00-c2d9f48862ed\",\"type\":\"items\"}"
11) "{\"uuid\":\"1228b8c2-e4cb-410f-89b9-2ef7ebfc76ba\",\"type\":\"items\"}"
12) "{\"uuid\":\"9008f555-2f23-4e73-9f2a-0c86852468a0\",\"type\":\"items\"}"

```

Verification of items being preserved: (unfortunately, it failed again)

```
[root@chard log]# cat pushmi_pullyu.log | egrep "^E,"
E, [2022-01-13T11:06:04.781517 #30676] ERROR -- : Authentication failed with response code 403 (OpenStack::Exception::Authentication)
E, [2022-01-13T11:06:06.112373 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:07.451440 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:08.866073 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:11.432565 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:12.693337 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:13.941228 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:15.105166 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:17.544764 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:18.632549 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:19.679703 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
E, [2022-01-13T11:06:20.753326 #30676] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)

```

That might be related to these particular items. In the morning, there is one item '6d93878f-c349-4db9-8224-978eff6b7a71' deposited into Swift with success. That means the PMPY is working well.

Further investigation is needed!

**Comment by pgwillia** [comment]
The full stack trace of the error is
```
E, [2022-01-11T19:52:13.324853 #29602] ERROR -- : undefined method `strip' for false:FalseClass (NoMethodError)
/usr/lib64/ruby/2.6.0/net/http/header.rb:21:in `block in initialize_http_header'
/usr/lib64/ruby/2.6.0/net/http/header.rb:16:in `each'
/usr/lib64/ruby/2.6.0/net/http/header.rb:16:in `initialize_http_header'
/usr/lib64/ruby/2.6.0/net/http/generic_request.rb:46:in `initialize'
/usr/lib64/ruby/2.6.0/net/http/request.rb:15:in `initialize'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:222:in `new'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:222:in `csreq'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/connection.rb:268:in `req'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/container.rb:22:in `container_metadata'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/container.rb:16:in `initialize'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/connection.rb:34:in `new'
/usr/lib64/ruby/gems/2.6.0/gems/openstack-3.3.21/lib/openstack/swift/connection.rb:34:in `container'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/swift_depositer.rb:26:in `deposit_file'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:198:in `block (2 levels) in run_preservation_cycle'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/aip.rb:19:in `create'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:196:in `block in run_preservation_cycle'
/usr/lib64/ruby/gems/2.6.0/gems/rollbar-3.3.0/lib/rollbar.rb:145:in `scoped'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:193:in `run_preservation_cycle'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:214:in `run_tick_loop'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:54:in `start_server'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:279:in `block in start_server_as_daemon'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:277:in `block in start_proc'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:281:in `start_proc'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/application.rb:307:in `start'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/controller.rb:56:in `run'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons.rb:199:in `block in run_proc'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons/cmdline.rb:124:in `catch_exceptions'
/usr/lib64/ruby/gems/2.6.0/gems/daemons-1.4.1/lib/daemons.rb:198:in `run_proc'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:277:in `start_server_as_daemon'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:34:in `run'
/usr/lib64/ruby/gems/2.6.0/gems/pushmi_pullyu-2.0.1/exe/pushmi_pullyu:7:in `<top (required)>'
/usr/bin/pushmi_pullyu:23:in `load'
/usr/bin/pushmi_pullyu:23:in `<main>'
```

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/pushmi_pullyu/blob/424fef9181b73cab3e98a56f96bedeffab2180a1/lib/pushmi_pullyu/swift_depositer.rb#L21

https://github.com/ruby-openstack/ruby-openstack/blob/373e0c47ab23b67c695873839282866d0849989a/lib/openstack/swift/container.rb#L19-L27

https://github.com/ruby-openstack/ruby-openstack/blob/373e0c47ab23b67c695873839282866d0849989a/lib/openstack/connection.rb#L210-L256

https://devdocs.io/ruby~2.6/net/httpheader#method-i-initialize_http_header

**Comment by pgwillia** [comment]
This looks like it might be a bug in the [openstack gem](https://github.com/ruby-openstack/ruby-openstack), which is no longer being maintained.  

I haven't been able to reproduce it, but it seems like the HTTP headers that are generated one of the values parsed is `false` when only Strings are expected.

I wonder if this is related to the OpenStack 403 response that occurs before the other failures.  It would be great to be able to see the corresponding OpenStack logs.

**Comment by pgwillia** [comment]
Duplicate https://github.com/ualbertalib/pushmi_pullyu/issues/311
